import React from 'react';
import Head from 'next/head';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import QueryProvider from './provider';
import NavBar from '@/components/common/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'SPL | 스플',
  description: 'Generated by SPL',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <Head>
        <script
          type='text/javascript'
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_API_KEY}&libraries=services`}
        ></script>
      </Head>
      <body className={inter.className}>
        <QueryProvider>
          <NavBar />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
