import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import QueryProvider from './provider';
import NavBar from '@/components/common/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang='ko' className='dark'>
    <html lang='ko'>
      <QueryProvider>
        <NavBar />
        <body className={inter.className}></body>
        {children}
      </QueryProvider>
    </html>
  );
}
